if(EXISTS "C:/Users/КристинаКюркчиева/source/repos/hw1-template/testing_tests-b12d07c.cmake")
  include("C:/Users/КристинаКюркчиева/source/repos/hw1-template/testing_tests-b12d07c.cmake")
else()
  add_test(testing_NOT_BUILT-b12d07c testing_NOT_BUILT-b12d07c)
endif()
